version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.progress.editing
    environment:
      ADDONS: "eea.progress.editing[test]"
      DEVELOP: "src/eea.progress.editing"
